Finish chapter 6: Modeling users
huuhunghienhoa/sample_app pull request #4
Opened 2018-02-21 09:02 UTC by huuhunghienhoa

ready
![screenshot from 2018-02-21 16-02-29](https://user-images.githubusercontent.com/18455114/36471333-ab19a722-1720-11e8-8ace-69567b81ea80.png)

2018-02-21 09:03 UTC, huuhunghienhoa commented
ready

2018-02-21 09:11 UTC, huuhunghienhoa commented
ready

2018-02-21 09:19 UTC, VuThiTranVan requested changes

2018-02-21 09:19 UTC, VuThiTranVan commented on app/models/user.rb
> +  validates :password, presence: true, length: {minimum: 6}
1. thứ tự các macro không đúng coding convention nhé.
Em check lại nhé
Link: https://github.com/framgia/coding-standards/blob/master/vn/rails/standard.md#activerecord

2. `maximum: 50`, `maximum: 255`
tìm hiểu về gem config và thực hiện setting lại chỗ này nhé

2018-02-21 09:19 UTC, VuThiTranVan commented on db/migrate/20180221045007_add_index_to_users_email.rb
> +end
aloo, file này để mần chi vậy?

2018-02-21 09:19 UTC, VuThiTranVan commented on test/models/user_test.rb
> +end
không dùng thì xóa đi em, để chi vậy

2018-02-21 09:19 UTC, VuThiTranVan commented
commented

2018-02-21 09:22 UTC, huuhunghienhoa commented on test/models/user_test.rb
> +end
File này em push lên rồi mới nhớ ra là chưa xóa :+1:

2018-02-21 09:25 UTC, huuhunghienhoa commented on db/migrate/20180221045007_add_index_to_users_email.rb
> +end
Tạo index cho trường Email phục vụ việc truy xuất database cho tìm kiếm nhanh hơn ấy chị.
Em tạo bằng generate migration tưởng đâu nó add cho dòng này add_index :users, :email, unique: true
Hình như phải add thủ công

2018-02-21 10:11 UTC, huuhunghienhoa commented
ready

2018-02-22 01:10 UTC, VuThiTranVan commented on db/migrate/20180221045007_add_index_to_users_email.rb
> +end
Không phải thủ công em nhé, do em chưa chạy đúng lệnh thôi.
Em nên tìm hiểu thêm về cơ chế trong migration của rails nhé

2018-02-22 01:14 UTC, VuThiTranVan commented on db/migrate/20180221045007_add_index_to_users_email.rb
> +end
Không phải em gõ thủ công code line 3 đâu nhé.
Do em chạy thiếu lệnh nên nó ko taooj ra được thôi 
Có time thì đọc về cơ chế migrate trong rails nhé

2018-02-22 01:14 UTC, VuThiTranVan commented
merged

2018-02-22 01:41 UTC, merged